language: node_js
node_js:
  - 12
branchs:
  only:
    - dev
cache:
  directories:
    - node_modules
before_script:
  - npm install hexo-cli
  - npm install
script:
  - hexo clean
  - hexo generate
deploy:
  on:
    branch: dev
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  local_dir: public
  target_branch: master
